ARG BUILD_FROM
FROM ${BUILD_FROM}

# Labels
LABEL \
    io.hass.name="TasUI" \
    io.hass.description="Discovery and manage Tasmota devices" \
    io.hass.type="addon" \
    io.hass.version=latest \
    io.hass.arch="amd64"